name = "Fruitycraft 2"
author = "frøya, bunya"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92cf37089f57f43bd2172625986c5b5629e4ab2803866bbcd9154def9b86b7f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
