name = "Fruitycraft 2"
author = "frøya, bunya"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07245073e5a1574d8db3538d14222520e592dd5b8beafc84ff1253481fa2e71d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
