name = "Fruitycraft 2"
author = "frøya, bunya"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc3965538458e8eda4a9324c73382f114185463abc9ba317d1edaad7329ef3a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
